services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: syncbox-server

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: syncbox-server-test
